# Copyright 2017 Graeme Gellatly
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import _, api, models


class SaleOrder(models.Model):
    _inherit = "sale.order"

    @api.depends(
        "procurement_group_id.stock_move_ids.created_production_id.procurement_group_id.mrp_production_ids"
    )
    def _compute_mrp_production_count(self):
        data = self.env["mrp.production"].read_group(
            [("sale_id", "in", self.ids), ("state", "!=", "cancel")],
            ["id"],
            ["sale_id"],
        )
        mrp_count = dict()
        for item in data:
            mrp_count[item["sale_id"][0]] = item["sale_id_count"]
        for sale in self:
            sale.mrp_production_count = mrp_count.get(sale.id)

    def action_view_mrp_production(self):
        self.ensure_one()
        mrp_production_ids = (
            self.env["mrp.production"].search([("sale_id", "=", self.id)]).ids
        )
        action = {
            "res_model": "mrp.production",
            "type": "ir.actions.act_window",
        }
        if len(mrp_production_ids) == 1:
            action.update(
                {
                    "view_mode": "form",
                    "res_id": mrp_production_ids[0],
                }
            )
        else:
            action.update(
                {
                    "name": _("Manufacturing Orders Generated by %s", self.name),
                    "domain": [("id", "in", mrp_production_ids)],
                    "view_mode": "tree,form",
                }
            )
        return action
